name: Feature Request
description: No, Stage Editor won't be added to the engine.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added to this engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested.
      options:
        - Proper credit that was forgotten
        - A thing that would not cause problems
        - Useful feature
        - Actual feedback
        - A good idea
        - Stage Editor
        - Better LUA mod support idea
        - Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)
    validations:
      required: true
